### ISSUE TITLE
大佬，请问这个是flutter运行uniapp打包的小程序吗，另外这个只支持运行一个小程序吗，能否像微信一样，运行多个小程序，通过动态的小程序资源包地址

### ISSUE THREAD

**Issue by wraptor** [yldebug/flutter_uniapp#1]

**Comment by yldebug** [comment]
可以运行多个，但是只能同时运行一个， 目前只集成了本地包模式，官方是支持动态下发小程序的，我还没有时间去集成

**Comment by wraptor** [comment]
大佬牛逼，已测可以打开小程序，不过有几个点，比如
- 打开会先灰屏再显示小程序，这种是否可以做logo+loading类似微信小程序那样
- 另外有些功能报错的是否集成sdk就可以，比如地图是空白的、video无法播放视频、打开有广告的页面报未添加ad模块等等

**Comment by yldebug** [comment]
好的 我抽时间搞一下 未添加模块这个，因为只集成了基础框架，并没有添加其他的模块， 所以在你自己的项目添加对应的sdk即可，如果我这边全部打包的话 会很大，所以需要什么模块自己导入即可，
